/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import { Scene } from "laya/display/Scene";
import { ClassUtils } from "laya/utils/ClassUtils";
var REG: Function = ClassUtils.regClass;
import { Sprite } from "laya/display/Sprite";
import { Animation } from "laya/display/Animation";
import { Text } from "laya/display/Text";
export module ui {
	export class MainUI extends Scene {
		public referenceClass:Array<any>=[Sprite, Animation, Text]; // 强制引用类,防止被编译器忽略
		constructor(){ super() }
	}
}
import { Label } from "laya/ui/Label";
export module ui.test {
    export class TestSceneUI extends Scene {
		public scoreLbl:Label;
		public tipLbll:Label;
        public static  uiView:any ={"type":"Scene","props":{"width":640,"runtime":"script/GameUI.ts","name":"gameBox","height":1136},"compId":1,"child":[{"type":"Sprite","props":{"y":1116,"x":-83,"width":805,"texture":"test/block.png","name":"ground","height":20},"compId":3,"child":[{"type":"Script","props":{"y":0,"x":0,"width":805,"label":"ground","height":20,"runtime":"laya.physics.BoxCollider"},"compId":5},{"type":"Script","props":{"type":"static","runtime":"laya.physics.RigidBody"},"compId":6}]},{"type":"Sprite","props":{"y":0,"x":0,"name":"gameBox"},"compId":18},{"type":"Sprite","props":{"y":0,"x":0,"name":"UI"},"compId":14,"child":[{"type":"Label","props":{"y":50,"x":158,"width":272,"var":"scoreLbl","height":47,"fontSize":40,"color":"#51c524","align":"center"},"compId":17},{"type":"Label","props":{"y":0,"x":0,"width":640,"var":"tipLbll","valign":"middle","text":"别让箱子掉下来\\n\\n点击屏幕开始游戏","height":1136,"fontSize":40,"color":"#c6302e","align":"center"},"compId":16}]},{"type":"Script","props":{"enabled":true,"dropBox":"@Prefab:prefab/DropBox.prefab","bullet":"@Prefab:prefab/Bullet.prefab","runtime":"script/GameControl.ts"},"compId":20}],"loadList":["test/block.png","prefab/DropBox.prefab","prefab/Bullet.prefab"],"loadList3D":[]};
        public referenceClass:Array<any>=[Label, Sprite]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(TestSceneUI.uiView);
        }
    }
    REG("ui.test.TestSceneUI",TestSceneUI);
}