/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Scroll from "./script/Scroll"
import RockSpawn from "./script/RockSpawn"
import GameUI from "./script/GameUI"
import GameControl from "./script/GameControl"
import Bullet from "./script/Bullet"
import DropBox from "./script/DropBox"
import RockScroll from "./script/RockScroll"
import { RigidBody } from "laya/physics/RigidBody"
import { ChainCollider } from "laya/physics/ChainCollider"
import { BoxCollider } from "laya/physics/BoxCollider"
import { CircleCollider } from "laya/physics/CircleCollider"
import { Text } from "laya/display/Text"
import { ClassUtils } from "laya/utils/ClassUtils";
import { ui } from "./ui/layaMaxUI";
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=800;
    static height:number=480;
    static scaleMode:string="exactfit";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Main.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = ClassUtils.regClass;
		reg("ui", ui);
        reg("script/Scroll.ts",Scroll);
        reg("script/RockSpawn.ts",RockSpawn);
        reg("script/GameUI.ts",GameUI);
        reg("script/GameControl.ts",GameControl);
        reg("script/Bullet.ts",Bullet);
        reg("script/DropBox.ts",DropBox);
        reg("script/RockScroll.ts",RockScroll);
        reg("laya.physics.RigidBody",RigidBody);
        reg("laya.physics.ChainCollider",ChainCollider);
        reg("laya.physics.BoxCollider",BoxCollider);
        reg("laya.physics.CircleCollider",CircleCollider);
        reg("laya.display.Text",Text);
    }
}
GameConfig.init();